-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            noise = 0.0,
            vibrancy = 0.13,
        },
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(bf404000)", "rgba(bf404000)"},
                angle = 45,
            },
        },
        gaps_in = 8,
        gaps_out = 15,
        resize_on_border = true,
    },
    input = {
        accel_profile = "flat",
        numlock_by_default = true,
        sensitivity = -0.0,
    },
})
